# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  HELM_EXPERIMENTAL_OCI: 1

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: HelmDeploy@0
  inputs:
    azureSubscriptionForACR: 'RMDev(c00d16c7-6c1f-4c03-9be1-6934a4c49682)'
    azureResourceGroupForACR: 'sonayak-rg'
    azureContainerRegistry: 'sonayak.azurecr.io'
    command: 'save'
    chartName: 'myworld'
    chartPath: './helloworld-chart'
